BEGIN;
CREATE TABLE IF NOT EXISTS "public"."notifications"(
    id SERIAL PRIMARY KEY,
    userid INT NOT NULL,
    message TEXT NOT NULL,
    is_read BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
COMMIT;
