BEGIN;

CREATE TABLE IF NOT EXISTS events (
    ID SERIAL PRIMARY KEY,
    UserID INT NOT NULL,
    Description VARCHAR(255) NOT NULL,
    Title VARCHAR(255) NOT NULL UNIQUE,
    Time DATE NOT NULL,
    Location VARCHAR(255) NOT NULL,
    Status VARCHAR(255) NOT NULL,
    Price DECIMAL(10, 2) NOT NULL,
    Category VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
    FOREIGN KEY (UserID) REFERENCES users(ID)
);

COMMIT;
