BEGIN;

CREATE TABLE IF NOT EXISTS events (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    UserID INT NOT NULL,
    Date DATE NOT NULL,
    Description VARCHAR(255) NOT NULL,
    Title VARCHAR(255) NOT NULL UNIQUE,
    Time TIME NOT NULL,
    Location VARCHAR(255) NOT NULL,
    Status VARCHAR(255) NOT NULL,
    Price DECIMAL(10, 2) NOT NULL,
    Category VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

COMMIT;
